# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=9090

# ===============================
# DATABASE CONFIGURATION (MySQL)
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
# CHANGE_THIS: Put your MySQL Workbench password here
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE (Auto Table Creation)
# ===============================
# This will automatically create/update tables (Users, Rides, etc.)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false

# ===============================
# JWT SECURITY CONFIGURATION
# ===============================
# This key must be long and secure (at least 32 chars)
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

# ===============================
# EMAIL CONFIGURATION (Gmail SMTP)
# ===============================
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
# CHANGE_THIS: Put the Gmail address that will SEND emails
spring.mail.username=${MAIL_USERNAME}
# CHANGE_THIS: Put the 16-digit App Password here (NOT your login password)
spring.mail.password=${MAIL_PASSWORD}


#Supabase(Cloud) configuration to store the files on cloud
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.bucket=KYC-Document

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000


#KYC encryption secret key - isko strong key me change karna hai
# 16-character secret key for AES encryption
app.security.encryption-key=${ENCRYPTION_KEY}

# Payment integration key
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}